# Generated by Django 4.2.30 on 2026-06-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Refunded', 'Refunded'), ('Close', 'Close'), ('Cancelled', 'Cancelled')], default='Open', max_length=9)),
            ],
            options={
                'db_table': 'api_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(unique=True)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Unpaid', 'Unpaid'), ('Complete', 'Complete')], default='Pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('variant_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order')),
            ],
            options={
                'db_table': 'api_orderitem',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('variant_id', models.IntegerField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.cart')),
            ],
        ),
    ]
