# Generated by Django 4.2.30 on 2026-05-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_alter_order_status_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(unique=True)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unpaid', 'Unpaid'), ('Complete', 'Complete')], default='Pending', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
        ),
    ]
