# Generated by Django 4.2.30 on 2026-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Refunded', 'Refunded'), ('Close', 'Close'), ('Cancelled', 'Cancelled')], default='Open', max_length=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Unpaid', 'Unpaid'), ('Complete', 'Complete')], default='Pending', max_length=8),
        ),
    ]
