services:

    emails:
        build: ./emails
        command: bash -c "uv run python3 manage.py runserver 0.0.0.0:8001"
        volumes:
            - ./emails:/app
            - /app/.venv
        ports:
            - 8001:8001
        restart: always
        depends_on:
            - emails-db
            - products-db
        networks:
            - microservices-network
    
    emails-consumer:
        build: ./emails
        command: uv run python3 manage.py start_consumer
        depends_on:
            - rabbitmq
            - products-db
        restart: always
        networks:
            - microservices-network

    products:
        build: ./products
        # command: bash -c "uv run python3 manage.py runserver 0.0.0.0:8002"
        command: >
            sh -c "uv run python3 manage.py seed_products &&
                uv run python3 manage.py runserver 0.0.0.0:8002"
        volumes:
            - ./products:/app
            - /app/.venv
        ports:
            - 8002:8002
        restart: always
        depends_on:
            - products-db
            - rabbitmq
        networks:
            - microservices-network
    
    products-consumer:
        build: ./products
        command: uv run python3 manage.py start_consumer
        depends_on:
            - rabbitmq
            - products-db
        restart: always
        networks:
            - microservices-network

    orders:
        build: ./orders
        # command: bash -c "uv run python3 manage.py runserver 0.0.0.0:8003"
        volumes:
            - ./orders:/app
            - /app/.venv
        ports:
            - 8003:8003
            - 5678:5678
        restart: always
        depends_on:
            - orders-db
            - auth-service
            - rabbitmq
        networks:
            - microservices-network

    auth-service:
        build: ./auth_service
        command: >
            sh -c "uv run python3 manage.py wait_for_db &&
             uv run python3 manage.py seed_users &&
             uv run python3 manage.py runserver 0.0.0.0:8004"
        volumes:
            - ./auth_service:/app
            - /app/.venv
        ports:
            - 8004:8004
        restart: always
        depends_on:
            - auth-service-db
        networks:
            - microservices-network

    emails-db:
        image: postgres:14.2-alpine
        restart: unless-stopped
        volumes:
            - .postgres_data/emails_data:/var/lib/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=admin
        ports:
            - "5432:5432"
        networks:
            - microservices-network

    orders-db:
        image: postgres:14.2-alpine
        restart: unless-stopped
        volumes:
            - .postgres_data/orders_data:/var/lib/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=admin
        ports:
            - "5433:5432"
        networks:
            - microservices-network

    products-db:
        image: postgres:14.2-alpine
        restart: unless-stopped
        volumes:
            - .postgres_data/products_data:/var/lib/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=admin
        ports:
            - "5434:5432"
        networks:
            - microservices-network

    auth-service-db:
        image: postgres:14.2-alpine
        restart: unless-stopped
        volumes:
            - .postgres_data/auth_data:/var/lib/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=admin
        ports:
            - "5435:5432"
        networks:
            - microservices-network

    rabbitmq:
        image: "rabbitmq:management"
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - microservices-network

networks:
    microservices-network:
        driver: bridge