# Generated by Django 4.2.30 on 2026-06-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red')], default='white', max_length=30)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('type', models.CharField(choices=[('NUL', 'NUL'), ('phone', 'Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet')], default='NUL', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=21, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant', to='api.product')),
            ],
            options={
                'db_table': 'api_products_variant',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant_inventory', to='api.productvariant')),
            ],
            options={
                'db_table': 'api_products_variant_inventory',
            },
        ),
    ]
