# Generated by Django 4.2.30 on 2026-06-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_category_productvariant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
    ]
