"""
Django settings for emails project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ

environment = environ.FileAwareEnv(
    DEBUG=(bool, True),
    SECRET_KEY=(str, None),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1", "0.0.0.0", "emails"]),
    EMAIL_HOST_PASSWORD=(str, None),
    EMAIL_HOST_USER=(str, None),
    DEFAULT_FROM_EMAIL=(str, None),
    PRODUCTS_SERVICE_URL=(str, "http://products:8002/"),
    AUTH_SERVICE_URL=(str, "http://auth-service:8004/"),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:3000"]),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / ".env")

# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = environment("SECRET_KEY")
ALLOWED_HOSTS = environment("ALLOWED_HOSTS")
CORS_ALLOWED_ORIGINS = environment("CORS_ALLOWED_ORIGINS")

DEBUG = environment("DEBUG")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "emails.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emails.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
import configparser

config = configparser.ConfigParser()
config.read("config.ini")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME", config["DATABASE"]["NAME"]),
        "USER": os.environ.get("DATABASE_USER", config["DATABASE"]["USER"]),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", config["DATABASE"]["PASSWORD"]),
        "HOST": os.environ.get("DATABASE_HOST", config["DATABASE"]["HOST"]),
        "PORT": os.environ.get("DATABASE_PORT", config["DATABASE"]["PORT"]),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ORIGIN_ALLOW_ALL = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = environment("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = environment("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = environment("DEFAULT_FROM_EMAIL")


PRODUCTS_SERVICE_URL = environment("PRODUCTS_SERVICE_URL")
AUTH_SERVICE_URL = environment("AUTH_SERVICE_URL")
